##spring.application.name=hexagonal-study
server:
  port: 8081
spring:
  mongodb:
    host: localhost
    port: 27017
    authentication-database: admin
    username: root
    password: example
    database: hexagonal-study
monteiro:
    client:
      address:
        url: http://localhost:8082/addresses


        
