##spring.application.name=hexagonal-study
server:
  port: 8081
spring:
  mongodb:
    host: localhost
    port: 27017
    authentication-database: admin
    username: root
    password: example
monteiro:
    client:
      address:
        url: http://locahost:8082/addresses


        
